// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIcc8J9pDZAx1eS1izp_kv90PljPKMrQg',
    appId: '1:763283954840:web:08ee5d10614c1e636dc4ed',
    messagingSenderId: '763283954840',
    projectId: 'petcare-app-c5dfc',
    authDomain: 'petcare-app-c5dfc.firebaseapp.com',
    storageBucket: 'petcare-app-c5dfc.firebasestorage.app',
    measurementId: 'G-S4SXE56C38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCns8S1ow91onFArjhUmRk1CaRlcrOrcEw',
    appId: '1:763283954840:android:9ebe152186cabff76dc4ed',
    messagingSenderId: '763283954840',
    projectId: 'petcare-app-c5dfc',
    storageBucket: 'petcare-app-c5dfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD01rN-agbuSS055CLcXavH-iXJu2jE1pQ',
    appId: '1:763283954840:ios:5a9fec8fad19fe296dc4ed',
    messagingSenderId: '763283954840',
    projectId: 'petcare-app-c5dfc',
    storageBucket: 'petcare-app-c5dfc.firebasestorage.app',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD01rN-agbuSS055CLcXavH-iXJu2jE1pQ',
    appId: '1:763283954840:ios:5a9fec8fad19fe296dc4ed',
    messagingSenderId: '763283954840',
    projectId: 'petcare-app-c5dfc',
    storageBucket: 'petcare-app-c5dfc.firebasestorage.app',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIcc8J9pDZAx1eS1izp_kv90PljPKMrQg',
    appId: '1:763283954840:web:4b3e7a80b0fd5aed6dc4ed',
    messagingSenderId: '763283954840',
    projectId: 'petcare-app-c5dfc',
    authDomain: 'petcare-app-c5dfc.firebaseapp.com',
    storageBucket: 'petcare-app-c5dfc.firebasestorage.app',
    measurementId: 'G-KX57ZRGP15',
  );
}
